[[items]]
pathspec = "**/*.rs"

[[items.transformers]]
RawCommand = "Rustfmt"

[[items]]
pathspec = "**/*.md"

[[items.transformers]]

[items.transformers.RawCommand.System]
command = "deno"
env = {}
args = ["fmt", "--ext", "md", "-"]

[[items]]
pathspec = "*.md"

[[items.transformers]]

[items.transformers.RawCommand.System]
command = "deno"
env = {}
args = ["fmt", "--ext", "md", "-"]
