[[items]]
pathspec = "**/*.rs"
transformers = [{External = "Rustfmt"}]

[[items]]
pathspec = "**/*.md"
transformers = [{External = "DenoFmt"}]

[[items]]
pathspec = "*.md"
transformers = [{External = "DenoFmt"}]

