[[items]]
pathspec = "**/*.rs"

[[items.transformers]]
RawCommand = "Rustfmt"

[[items]]
pathspec = "**/*.md"

[[items.transformers]]
RawCommand = "DenoFmt"

[[items]]
pathspec = "*.md"

[[items.transformers]]
RawCommand = "DenoFmt"
