[[items]]
pathspec = "**/*.rs"

[[items.transformers]]
External = "Rustfmt"

[[items]]
pathspec = "**/*.md"

[[items.transformers]]
External = "DenoFmt"

[[items]]
pathspec = "*.md"

[[items.transformers]]
External = "DenoFmt"
