[package]
name = "yact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
false = "0.0.0"
git2 = {version = "0.18.1", default_features = false}
