[package]
name = "yact"
version = "2.3.2"
edition = "2021"
readme = "README.md"
license = "GPL-3.0-or-later"
authors = ["Nelson Penn"]
description = "Yet Another Commit Transformer: a tool for formatting staged files with minimal disturbance to developer workflow."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true

[dependencies]
clap = { version = "4.5.16", features = ["derive", "cargo"], optional = true }
git2 = { version = "0.20.4", default-features = false }
glob = "0.3.1"
semver = { version = "1.0.24", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8.19"

[features]
default = ["cli"]
cli = ["clap"]

# Used for creating temporary directories in unit tests
[dev-dependencies.uuid]
version = "1.10.0"
features = ["v4"]
