# Configuration file for yact. See https://github.com/NelsonAPenn/yact for more
# information.
#
# Created from the C / C++ sample config file.
items = [
    { glob = "**/*.cpp", transformers = ["ClangFormat"] },
    { glob = "**/*.hpp", transformers = ["ClangFormat"] },
    { glob = "**/*.h", transformers = ["ClangFormat"] },
    { glob = "**/*.c", transformers = ["ClangFormat"] },

    # clang-format also works for JSON. If it's already installed, may as well
    # use it rather than configuring a different tool.
    { glob = "**/*.json", transformers = ["ClangFormat"] },
   
    { glob = "**/*.md", transformers = ["TrailingWhitespace"] },
]
