# Configuration file for yact. See https://github.com/NelsonAPenn/yact for more
# information.
#
# Created from the Golang sample config file.
[[items]]
glob = "**/*.go"
transformers = ["Gofmt"]

[[items]]
glob = "**/*.md"
transformers = ["TrailingWhitespace"]
